 
/*Code generated by C-OOP
Copyright(C) 2024 Shivashish Das */

#define Main __Main
typedef struct ___Main __Main;
struct ___Main {
int a;
int b;
void (*main) ();
void (*hehe) (struct ___Main* this,int a);
};
__Main* _Main = {0};
#define Hello __Hello
typedef struct ___Hello __Hello;
struct ___Hello {
int c;
int d;
};
__Hello* _Hello = {0};
void* new_object(void*, unsigned long, ...);
Main* fn_construc_Main (__Main* this); 
void fn_628130 (){
Main* m = new_object(fn_construc_Main, sizeof(struct ___Main));
;printf("Hello World");}
void fn_692414 (struct ___Main* this,int a){
this->a = a;}
Hello* fn_construc_Hello (__Hello* this); 
struct ___Main* fn_construc_Main (struct ___Main* this) {
this->a = 90;
this->b = 90;
this->hehe = fn_692414;
return this;
}struct ___Main* fn_construc_Mainstatic (struct ___Main* this){
this->main = fn_628130;
return this;
}struct ___Hello* fn_construc_Hello (struct ___Hello* this) {
this->c = 90;
this->d = 100;
return this;
}struct ___Hello* fn_construc_Hellostatic (struct ___Hello* this){
return this;
}int main(int argc, const char** argv) {
_Main = calloc(1, sizeof(struct ___Main));
 _Main = fn_construc_Mainstatic(_Main);
_Hello = calloc(1, sizeof(struct ___Hello));
 _Hello = fn_construc_Hellostatic(_Hello);
_Main->main();
}
